### ISSUE TITLE
Aileron moves rudder

### ISSUE THREAD

**Issue by D-ECHO** [it0uchpods/IDG-MD-11X#1]
### Expected Behavior

Aileron input should move only the aileron, rudder input only rudder

### Current Behavior

When moving the aileron, the rudder moves into the opposite direction. Moving the rudder axis does not anything (well, it makes the rudder jitter, but it always gets back to the position selected by the aileron in parts of a second).

### Possible Solution

No
### Steps to Reproduce

1. Start the sim.
2. Move Aileron
3.
4.

**Comment by Wecsje** [comment]
Added to the to-do list, fix coming shortly.

C.

**Comment by D-ECHO** [comment]
Thx

**Comment by PSVAAirlines** [comment]
Ya, I saw it. We can not taxi after landing or on t/o......... Really bad! Hope it be fix soon. I can not handle even crosswinds..... LOL.

**Comment by Wecsje** [comment]
As said already, fix is coming shortly, we are working on it as we speak.

**Comment by it0uchpods** [comment]
Hi everyone,
I found the fix, the aileron-crosswind componet for autoland was backfeeding when disabled, so I've corrected that now.

Working on fixing another issue with the flight controls now, will let you know.

Kind Regards,
Josh

**Comment by PSVAAirlines** [comment]
thx, Octal........

**Comment by Wecsje** [comment]
Right, issue is solved, will be pushed shortly, together with the other fix.

Regards,

Charlie (Wecsje)

**Comment by it0uchpods** [comment]
Issue is now fixed, thanks

Kind Regards,
Josh
